### ISSUE TITLE
Support for Auto-layout columns

### ISSUE THREAD

**Issue by wschwaiger** [ErdmannFreunde/euf_grid#9]
Hi,

Have you planned to add support for auto-layout-columns in the near future? https://getbootstrap.com/docs/4.0/layout/grid/#auto-layout-columns

Many thanks,
Wolfgang

**Comment by bastibuck** [comment]
Hey, you can actually use this extension with any CSS-Framework if you want since it only adds the given classes to the elements. 

There is a config file that you can voerwrite in your config somewhere so you can set your desired classes to appear in the select fields. If you include e.g. Bootstrap it should work just fine. 

Cannot say anything about the included CSS-Framework though

**Comment by denniserdmann** [comment]
auto-layout classes like `col` or `col-md` will come in the following version, see https://github.com/ErdmannFreunde/euf_grid/commit/0c316b802c18a991e6007dd743853aaeb5e7b80e

**Comment by denniserdmann** [comment]
added in Version 2.2.2
